# appendices(??) ??
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#appendix

spring:
  # h2.console.enabled: true => h2 console ?? ??(=? ?????? h2 ?? ?? ??)
  # h2.console.enabled.path: /h2 => h2 console ??? ?? url ??(??)
  h2:
    console:
      enabled: true
      path: /h2
  # datasource.url: jdbc:h2:mem:test => ??? jdbc url ? ??(??)
  datasource:
    url: jdbc:h2:mem:test
  # spring.sql.init.data-locations: classpath*:db/h2/schema.sql
  #  => ?????? ?? ?, ?? ??(src/main/resources/db/h2/)? ?? .sql ??(schema.sql)? ???? ????
  #  => .sql ??(schema.sql)? ??????? DB(h2)? ???? ???? ????? ??
  ##  => JPA ? ??? ? ?? ????? ???? ??? ??.
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
# HTTP responses ? charset encoding ? ???? ??. ?? ?? charset ?? ? ?? ?? ????.
## => ??? ?? ??? ????? charset = UTF-8? ???? ????.
server:
  servlet:
    encoding:
      force-response: true